import { useEffect, useState } from 'react';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, TextField } from '@mui/material';
import CrudPage from '../components/CrudPage';
import LookupSelect from '../components/LookupSelect';
import { branchApi } from '../services/crmApi';
import { useCompanies } from '../hooks/useLookups';

const fields=[{field:'name',header:'Branch Name'},{field:'code',header:'Branch Code'},{field:'companyId',header:'Company ID'},{field:'email',header:'Email'},{field:'phone',header:'Phone'},{field:'address',header:'Address'}];
function BranchForm({open,initialValues={},onClose,onSubmit}){const [form,setForm]=useState(initialValues);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const companies=useCompanies();useEffect(()=>{setForm(initialValues||{});setError('')},[initialValues,open]);const set=(k,v)=>setForm(x=>({...x,[k]:v}));const submit=async e=>{e.preventDefault();setSaving(true);try{await onSubmit(form)}catch(x){setError(x.response?.data?.message||x.message||'Unable to save branch')}finally{setSaving(false)}};return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Branch</DialogTitle><form onSubmit={submit}><DialogContent>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Grid container spacing={2}><Grid item xs={12}><TextField fullWidth required label="Branch Name" value={form.name||''} onChange={e=>set('name',e.target.value)}/></Grid><Grid item xs={12} md={6}><TextField fullWidth required label="Branch Code" value={form.code||''} onChange={e=>set('code',e.target.value)}/></Grid><Grid item xs={12} md={6}><LookupSelect required label="Company" value={form.companyId} options={companies.options} loading={companies.loading} onChange={v=>set('companyId',v)}/></Grid><Grid item xs={12} md={6}><TextField fullWidth label="Email" type="email" value={form.email||''} onChange={e=>set('email',e.target.value)}/></Grid><Grid item xs={12} md={6}><TextField fullWidth label="Phone" value={form.phone||''} onChange={e=>set('phone',e.target.value)}/></Grid><Grid item xs={12}><TextField fullWidth label="Address" value={form.address||''} onChange={e=>set('address',e.target.value)}/></Grid></Grid></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button type="submit" variant="contained" disabled={saving}>{saving?'Saving...':'Save'}</Button></DialogActions></form></Dialog>}
export default function Branch(){return <CrudPage title="Branches" api={branchApi} columns={fields} fields={fields} FormComponent={BranchForm}/>}
