import { useEffect, useState } from 'react';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, TextField } from '@mui/material';
import CrudPage from '../components/CrudPage';
import LookupSelect from '../components/LookupSelect';
import { departmentApi } from '../services/crmApi';
import { useBranches, useCompanies } from '../hooks/useLookups';

const fields=[{field:'name',header:'Department Name'},{field:'code',header:'Department Code'},{field:'companyId',header:'Company ID'},{field:'branchId',header:'Branch ID'},{field:'description',header:'Description'}];
function DepartmentForm({open,initialValues={},onClose,onSubmit}){const [form,setForm]=useState(initialValues);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const companies=useCompanies();const branches=useBranches(form.companyId);useEffect(()=>{setForm(initialValues||{});setError('')},[initialValues,open]);const set=(k,v)=>setForm(x=>({...x,[k]:v}));const companyChange=v=>setForm(x=>({...x,companyId:v,branchId:''}));const submit=async e=>{e.preventDefault();setSaving(true);try{await onSubmit(form)}catch(x){setError(x.response?.data?.message||x.message||'Unable to save department')}finally{setSaving(false)}};return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Department</DialogTitle><form onSubmit={submit}><DialogContent>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Grid container spacing={2}><Grid item xs={12}><TextField fullWidth required label="Department Name" value={form.name||''} onChange={e=>set('name',e.target.value)}/></Grid><Grid item xs={12} md={6}><TextField fullWidth required label="Department Code" value={form.code||''} onChange={e=>set('code',e.target.value)}/></Grid><Grid item xs={12} md={6}><LookupSelect required label="Company" value={form.companyId} options={companies.options} loading={companies.loading} onChange={companyChange}/></Grid><Grid item xs={12}><LookupSelect required label="Branch" value={form.branchId} options={branches.options} loading={branches.loading} disabled={!form.companyId} onChange={v=>set('branchId',v)}/></Grid><Grid item xs={12}><TextField fullWidth multiline minRows={3} label="Description" value={form.description||''} onChange={e=>set('description',e.target.value)}/></Grid></Grid></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button type="submit" variant="contained" disabled={saving}>{saving?'Saving...':'Save'}</Button></DialogActions></form></Dialog>}
export default function Department(){return <CrudPage title="Departments" api={departmentApi} columns={fields} fields={fields}/>}
